version: "3"
services:
  app:
    container_name: boleta
    restart: always
    build: .
    ports:
      - "62000:62000"
    depends_on:
      - "postgres"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=boleta
      - FIRST_USER_NAME
      - FIRST_USER_EMAIL
      - FIRST_USER_PASS
      - TOKEN_SECRET
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=boleta
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
networks:
  default:
    external:
      name: all-apps
volumes:
  pgdata:

# PGDATA
# POSTGRES_INITDB_ARGS