version: "3"
services:
  app:
    container_name: boleta
    restart: always
    build: .
    ports:
      - "62000:62000"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DB_URL
      - DB_PORT
      - TOKEN_SECRET
networks:
  default:
    external:
      name: all-apps